### ISSUE TITLE
FP Metric Error Discussion

### ISSUE THREAD

**Issue by Pamphlett** [lewisjiang/contour-context#1]
Hi @lewisjiang,

Thanks so much for sharing your brilliant work. I am impressed by the discussion part of the paper (section V. C), which is really inspiring and grounded. I mean, you stand on the practitioner's point of view (real-world deployment).

Just have one tiny question regarding the discussion. In the evaluation protocol you've chosen, which is the third among the three, FPs are defined as:
1. similarity score above one threshold;
2. spacial distance bigger than l_3 (which is 5m).
So how could the translation error of FPs in Fig. 7 be smaller than 5m? Please correct me if there's something I got wrong.

**Comment by lewisjiang** [comment]
Hi @Pamphlett,

Thank you for your interest in our work. It's worth noting that **translation** $\neq$ **translation (estimation) error**.

Assume we have points $A$ and $B$ living in $\mathbb{R}^{3}$, and let $A=[1,0,0]$, $B=[6,0,0]$. Then the relative translation $BA=[5,0,0]$. Now if an estimate of $BA$ is somehow $\hat{BA}=[5.1, 0,0]$, then the L2 norm of relative translation estimation error is $\|BA-\hat{BA} \|_2 = 0.1$. The point of discussion in section V. C is that even at times of large $\|BA\|_2$, we could still have small $\|BA-\hat{BA} \|_2$.

Hope this answers your question.

**Comment by Pamphlett** [comment]
Thanks for your prompt reply.

So basically you are saying that even if the two scans (current and query) are distant from each other, which could be rejected as FP by the protocol, they could still have a rather accurate initial guess from your algo and be fed to the subsequent ICP.

**Comment by lewisjiang** [comment]
@Pamphlett Yes.

**Comment by Pamphlett** [comment]
Got it, thanks!
