### ISSUE TITLE
Demo video compare with scan-context

### ISSUE THREAD

**Issue by chengwei0427** [lewisjiang/contour-context#2]
Hi,  
   Thanks for sharing the great work!
   The **contour-context** integration for lego-loam  works well, and a test video is [here](https://www.bilibili.com/video/BV1a54y1c7D5/?spm_id_from=333.337.search-card.all.click&vd_source=438f630fe29bd5049b24c7f05b1bcaa3).

**Comment by lewisjiang** [comment]
@chengwei0427 Thank you for your interest in our work!
