### ISSUE TITLE
Anchor CA

### ISSUE THREAD

**Issue by hogyun2** [lewisjiang/contour-context#4]
Hello. Thank you very much for your good research. 
I understood that one anchor is created for each frame of pointcloud by reading the paper and looking at the code. Then, what is the criteria for selecting one anchor among the various CA?

**Comment by lewisjiang** [comment]
@hogyun2 In fact we slice a point cloud into multiple levels and top (by area) CAs at some levels are anchors. As described in the paper (Sec V.B.3, complexity analysis), we select 3x6=18 anchors for each scan.

**Comment by hogyun2** [comment]
Thank you for your answer.
Then, as I understand it, each scan will generate a graph (constellation) for one anchor, and 18 retrival keys. Then, when I revisit, I wonder which key is used for loop detection out of 18 retroval keys.
If I am mistaken, could you explain the process of loop detection?

**Comment by lewisjiang** [comment]
@hogyun2 Actually each anchor has an associated retrieval key and a local graph/constellation connection, as is shown in Fig.3 of the paper. When revisiting, all the keys in the query scan will be used.

**Comment by hogyun2** [comment]
@lewisjiang Thank you for your answer.
In fact, is it comparing the constellation with the 18 retrival keys of query scan and candidates scan?
Then, is recognized the revisited place determined by the average value of the comparison between query scan and candidates scan?

**Comment by lewisjiang** [comment]
@hogyun2 The number of comparison times is not definite, cuz at first the matching is a search with a maximum distance. The correlation value between query and candidate calculated from GMM optimization together with a given threshold jointly determines if a match is positive.

**Comment by euncheolChoi** [comment]
@lewisjiang
 I have a question about something similar. 
As I understand it, for one LiDAR SCAN data, there are 16 Anchor CAs and a structure of CACs connected to each Anchor CA. (16 CACs exist)
I understood this 'structure of 16 CACs' as a descriptor of the scene, and I'm wondering how to compare these descriptors. 
For each of the 16 CACs, the GMM will give me a Correlation value, and then  sum up all 16 Similarity values and compare them with the Threshold value to get the final pari?

thank you in advance.

**Comment by hogyun2** [comment]
@lewisjiang Thank you for your answer!
I'll read it again carefully based on the advices you referred to me. Thank you.
