### ISSUE TITLE
Some confusing results about MulRan Dataset

### ISSUE THREAD

**Issue by Viot-HUST** [lewisjiang/contour-context#5]
Hello, thank you for your excellent work! 
Recently, I have been reproducing the results of this method on the MulRan dataset, but have obtained confusing results, with TP consistently being 0 on MulRan Kaist01 and MulRan Riverside02. I ensure to follow the corresponding steps, but I am not sure if I have encountered any unexpected problems. By the way, some results on KITTI seem normal. Could you give me some help? Thank you very much!

**Comment by lewisjiang** [comment]
Hi, thank you for trying out our code. I cannot pin down the problem according to your account. Please provide more details such as console output. You can set `max_elapse_` and `min_elapse_` to 0 to bring forward the earliest valid loop closure.

Also, I'm considering to refactor the code to ease the pain of manually adapting code for different datasets in near future. Please stay tuned.
