### ISSUE TITLE
the problem of parameters tuning

### ISSUE THREAD

**Issue by Snow-know-nothing** [lewisjiang/contour-context#9]
Hello. Thank you for your excellent work. I want to test the impact of some parameters. I modified some parameters as shown below：
```
q_levels_: [1]
lv_grads_: [1.5, 2, 2.5, 3]
```
and in contour_mng.h：
```
const int8_t DIST_BIN_LAYERS[] = {1};  
const float LAYER_AREA_WEIGHTS[] = {0.3};
```
Then when algorithm detect some candidates, there will be a error like:
```
Cand id:4, @max# 9 votes, area perc: 0.059583, 
[3]    3227731 segmentation fault (core dumped)  rosrun cont2 cont2_batch_bin_test
```
Actually, when the parameter number in `lv_grads_` is more than 4, it will be OK. I just confused, did I miss some other parameters need to modify?

**Comment by lewisjiang** [comment]
Which levels ([1, 2, 3, 4]) to generate GMM is hardcoded as the default value of `GMMOptConfig` in `correlation.h`.

**Comment by snow-know** [comment]
Oh I found it, thank you very much!
